# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oe < Formula
  desc "The Opportunity Encoder command line"
  homepage "https://opportunity-encoder-production.up.railway.app"
  version "0.1.533"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eidra-umain/homebrew-oe/releases/download/cli-v0.1.533/oe_darwin_amd64.tar.gz"
      sha256 "7e707321111a5fb33d14e8b5f86c9b0a612ca3418a284e5f3061a59ccb4defbe"

      define_method(:install) do
        bin.install "oe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eidra-umain/homebrew-oe/releases/download/cli-v0.1.533/oe_darwin_arm64.tar.gz"
      sha256 "8a7d48ff0a5c929e658d7f524fd5afed42fe5632c33abae367d79f1f0c1baaa4"

      define_method(:install) do
        bin.install "oe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eidra-umain/homebrew-oe/releases/download/cli-v0.1.533/oe_linux_amd64.tar.gz"
      sha256 "5d6f8e9a09f6ac05d41a588674e7bf70450a6bfe510b1aff0679b212fd1a37f8"
      define_method(:install) do
        bin.install "oe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eidra-umain/homebrew-oe/releases/download/cli-v0.1.533/oe_linux_arm64.tar.gz"
      sha256 "df1c0df6ed08f1ffad72f7e28c0033ceeb2fd09f7079b011d09e10ce5b2e173f"
      define_method(:install) do
        bin.install "oe"
      end
    end
  end

  def caveats
    <<~EOS
      Sign in with: oe login
    EOS
  end

  test do
    system "#{bin}/oe", "tools", "version"
  end
end
