# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oe < Formula
  desc "The Opportunity Encoder command line"
  homepage "https://opportunity-encoder-production.up.railway.app"
  version "0.1.525"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eidra-umain/homebrew-oe/releases/download/cli-v0.1.525/oe_0.1.525_darwin_amd64.tar.gz"
      sha256 "6d717ebc838bd6a2c6a9195f4f2588677f16fe1afd41da1e6fb85c523d4e70c3"

      define_method(:install) do
        bin.install "oe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eidra-umain/homebrew-oe/releases/download/cli-v0.1.525/oe_0.1.525_darwin_arm64.tar.gz"
      sha256 "65336674f0dd76368d6d793fbcb4906f1ed46f15b30aef5b858887ba66ad9f74"

      define_method(:install) do
        bin.install "oe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eidra-umain/homebrew-oe/releases/download/cli-v0.1.525/oe_0.1.525_linux_amd64.tar.gz"
      sha256 "4675e35552646fa72ec73072316b409dd3a8c3653e57165bbb8e9d833468aaa1"
      define_method(:install) do
        bin.install "oe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eidra-umain/homebrew-oe/releases/download/cli-v0.1.525/oe_0.1.525_linux_arm64.tar.gz"
      sha256 "420c52665f744cd310a416c2a617ace70239f06d4c800945e4c7a6fbaab01950"
      define_method(:install) do
        bin.install "oe"
      end
    end
  end

  def caveats
    <<~EOS
      Sign in with: oe login
    EOS
  end

  test do
    system "#{bin}/oe", "tools", "version"
  end
end
