# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oe < Formula
  desc "The Opportunity Encoder command line"
  homepage "https://opportunity-encoder-production.up.railway.app"
  version "0.1.528"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eidra-umain/homebrew-oe/releases/download/cli-v0.1.528/oe_darwin_amd64.tar.gz"
      sha256 "3dc2cfccc5648c3408136ebe8d989bce4a1910f7c10810ed0ce57c039df4488a"

      define_method(:install) do
        bin.install "oe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eidra-umain/homebrew-oe/releases/download/cli-v0.1.528/oe_darwin_arm64.tar.gz"
      sha256 "5d60ec54dae57773b2c3139bcc24ddd30c8ccddad1a1339955ec6e9707d6eb94"

      define_method(:install) do
        bin.install "oe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eidra-umain/homebrew-oe/releases/download/cli-v0.1.528/oe_linux_amd64.tar.gz"
      sha256 "38f4740e550d43c7553300889a78200b04b4d4f01071801199ff86255d2aeaec"
      define_method(:install) do
        bin.install "oe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eidra-umain/homebrew-oe/releases/download/cli-v0.1.528/oe_linux_arm64.tar.gz"
      sha256 "b8a6d6c4234179c98bd5dac09ac263585d673da63e6085cf49d825aab6df3e1e"
      define_method(:install) do
        bin.install "oe"
      end
    end
  end

  def caveats
    <<~EOS
      Sign in with: oe login
    EOS
  end

  test do
    system "#{bin}/oe", "tools", "version"
  end
end
